export const ADDORDERTOQUEUE = "ADDORDERTOQUEUE";
export const UPDATEORDERTOQUEUE = "UPDATEORDERTOQUEUE";
export const DELETEORDERFROMQUEUE = "DELETEORDERFROMQUEUE";
export const PROCESSORDERFROMQUEUE = "PROCESSORDERFROMQUEUE";
export const RESETORDERQUEUE = "RESETORDERQUEUE";
export const RESETPROCESSQUEUE = "RESETPROCESSQUEUE";
